sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=b225ccc/docker-baseimage-xenial

install: true

before_script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .

script:
  - docker run -d --name base $REPO:$COMMIT
  - docker ps | grep -q base

after_success:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
